"""Shared OS foundations and transferable problem-solving skills."""
from .schema import B, concept as C, step as S, example as E, lab as P, quiz as Q, lesson as L

LESSONS = [
L('OS-C01',B('Qué hace un sistema operativo','What an operating system does'),B('¿Qué ocurre entre pulsar Guardar y recuperar tu archivo?','What happens between pressing Save and retrieving your file?'),B('Relacionar aplicación, proceso, sistema operativo y dispositivo.','Relate applications, processes, the operating system and devices.'),[
 C(B('Un mediador con responsabilidades','A mediator with responsibilities'),B('Una aplicación pide servicios: abrir un archivo, reservar memoria o enviar datos. El sistema operativo administra recursos compartidos y aplica restricciones a esas peticiones. El kernel es la parte privilegiada; las herramientas de administración y las aplicaciones no son el kernel. Piensa en una ciudad: las aplicaciones solicitan servicios y existen reglas comunes. La analogía acaba ahí: el sistema ejecuta instrucciones, no comprende intenciones ni garantiza que el contenido sea correcto.','An application requests services: opening files, allocating memory or sending data. The operating system manages shared resources and enforces restrictions on requests. The kernel is the privileged component; administration tools and applications are not the kernel. Think of a city whose applications request services under shared rules. The analogy stops there: the system executes instructions, not intentions, and cannot guarantee that content is correct.'),B('Aplicación, kernel y herramienta administrativa no son sinónimos.','Application, kernel and administrative tool are not synonyms.')),
 C(B('Programa y proceso','Program and process'),B('El programa almacenado contiene instrucciones; un proceso es una instancia en ejecución con identidad, memoria y recursos abiertos. Dos ventanas pueden pertenecer al mismo proceso, y una aplicación puede usar varios. Un PID ayuda a localizar una instancia durante un intervalo, pero se reutiliza. Compara nombre, identidad, ruta y contexto antes de decidir que un proceso es legítimo.','A stored program contains instructions; a process is a running instance with identity, memory and open resources. Two windows can belong to one process, while one application can use several. A PID identifies an instance during an interval but can be reused. Compare name, identity, path and context before considering a process legitimate.'),B('Archivo ejecutable no equivale a instancia ejecutándose.','An executable file is not a running instance.')),
 C(B('Persistencia y confirmación','Persistence and confirmation'),B('Guardar requiere resolver una ruta, comprobar permisos y escribir mediante las capas de almacenamiento. Cachés, formatos y fallos importan. Un mensaje de éxito es evidencia de una etapa, no una copia de seguridad. Comprueba que puedes reabrir el contenido esperado; para recuperación, restaura una copia independiente en otro destino. Un hash compara bytes, pero no demuestra todos los permisos ni quién creó el archivo.','Saving requires resolving a path, checking permissions and writing through storage layers. Caches, formats and failures matter. A success message is evidence of one stage, not a backup. Reopen the expected content; for recovery, restore an independent copy elsewhere. A hash compares bytes, not all permissions or the identity of the file author.'),B('Verifica el resultado y distingue guardar de respaldar.','Verify the result and distinguish saving from backing up.'))],
 [B('Aplicación','Application'),B('Proceso e identidad','Process and identity'),B('SO y permisos','OS and permissions'),B('Almacenamiento','Storage')],
 E(B('Un documento de ensayo','A trial document'),'GUI', '',B('Un archivo de texto ficticio que se puede cerrar y reabrir.','A fictitious text file that can be closed and reopened.'),B('Crea una carpeta del curso en tu perfil, escribe dos líneas y guarda. Cierra solo tu editor y reabre el archivo por su ruta. Anota dónde se conserva cada cosa: programa, proceso, archivo y nota de evidencia.','Create a course folder in your profile, type two lines and save. Close only your editor and reopen the file by its path. Record where each item exists: program, process, file and evidence note.')),
 P(B('Cualquier SO, editor de texto y cuenta estándar. Datos ficticios.','Any OS, text editor and standard account. Fictitious data.'),[
 S(B('Predice qué seguirá existiendo al cerrar el editor.','Predict what will remain after closing the editor.'),B('Diferencia el proceso del archivo guardado.','Distinguish the process from the saved file.')),
 S(B('Ejecuta el ejemplo y verifica el contenido reabierto.','Perform the example and verify the reopened content.'),B('Dos líneas correctas y ruta registrada.','Two correct lines and a recorded path.')),
 S(B('Describe qué pasaría si solo existiera esa copia y fallara el disco.','Describe what would happen if this were the only copy and the disk failed.'),B('Explicación de un dominio de fallo.','Explanation of a failure domain.'))],B('Ruta de ensayo, dos observaciones y esquema de capas.','Trial path, two observations and a layer diagram.'),B('Puedes explicar Guardar sin reducirlo a un botón.','Explain Save beyond the button.'),B('Conserva la evidencia y elimina solo tu documento ficticio.','Keep evidence and remove only your fictitious document.'),B('No localizas dónde guardaste.','You cannot locate where you saved.'),B('Consulta ubicación y nombre exactos antes de repetir la operación.','Check the exact location and name before repeating.')),
 Q(B('¿Cerrar el editor debe borrar el archivo guardado?','Should closing the editor delete the saved file?'),[B('Sí, proceso y archivo son iguales.','Yes, process and file are the same.'),B('No: son objetos distintos.','No: they are different objects.')],1,B('La vida del proceso y la persistencia del archivo tienen reglas distintas.','Process lifetime and file persistence follow different rules.')),B('Confundir interfaz con mecanismo.','Confusing the interface with its mechanism.'),B('Observa objetos y transiciones, no solo pantallas.','Observe objects and transitions, not just screens.'),['os-book'],['M02','M03']),
L('OS-C02',B('Contexto, privilegios y laboratorio','Context, privileges and laboratory'),B('¿Tu terminal está en el portátil, una VM o un servidor?','Is your terminal on the laptop, a VM or a server?'),B('Identificar dónde se ejecuta una acción y limitar su alcance.','Identify where an action runs and limit its scope.'),[
 C(B('Interfaz y lugar de ejecución','Interface and execution location'),B('Terminal es la interfaz; shell es el intérprete; un comando puede ser interno, alias o ejecutable. SSH puede mostrar una consola remota dentro de tu pantalla local. Cambiar de carpeta no cambia la identidad. Antes de actuar registra host, SO, arquitectura, shell, cuenta y directorio. Una instrucción correcta para otro sistema puede fallar sin que tu equipo esté roto.','A terminal is the interface; a shell is the interpreter; a command may be a built-in, alias or executable. SSH can display a remote console on your local screen. Changing folders does not change identity. Record host, OS, architecture, shell, account and working directory. An instruction for another system can fail without your computer being broken.'),B('Identifica el contexto antes del comando.','Identify context before the command.')),
 C(B('Privilegio mínimo','Least privilege'),B('Una cuenta estándar debe poder realizar las tareas ordinarias. Elevar permisos amplía el impacto y requiere una razón. Ante acceso denegado, pregunta si la acción está autorizada y qué recurso la bloquea; no respondas desactivando protecciones. La autorización de una práctica no se extiende a equipos vecinos, redes públicas o datos personales.','A standard account should handle ordinary tasks. Elevation increases impact and requires a reason. On access denied, ask whether the action is authorized and which resource blocks it; do not disable protection as a response. Lab authorization does not extend to neighboring devices, public networks or personal data.'),B('Un error de permisos puede ser un control funcionando.','A permission error may be a working control.')),
 C(B('Entorno reversible','A reversible environment'),B('Una VM separa recursos del anfitrión, pero carpetas compartidas, portapapeles y redes pueden volver a conectarlos. Usa red interna para los servicios del ejercicio y acceso de actualización controlado. Snapshot, backup y evidencia no son equivalentes. Prueba la restauración antes de tocar usuarios, firewall o arranque; guarda el cuaderno fuera de la VM que restaurarás.','A VM separates host resources, but shared folders, clipboard and networks can reconnect them. Use an internal network for lab services and controlled update access. Snapshot, backup and evidence are not equivalent. Test recovery before changing users, firewall or boot; keep notes outside the VM you will restore.'),B('Aislar, comprobar y poder volver atrás.','Isolate, verify and be able to return.'))],
 [B('Anfitrión','Host'),B('Hipervisor','Hypervisor'),B('SO invitado','Guest OS'),B('Carpeta de ensayo','Trial folder')],
 E(B('Ficha de entorno','Environment record'),'GUI / CLI','',B('Seis campos: host, SO, arquitectura, shell, identidad y ruta.','Six fields: host, OS, architecture, shell, identity and path.'),B('Consulta Acerca de/Información del sistema y compáralo con la terminal correspondiente. En Linux: uname -m e id. En PowerShell: $PSVersionTable y whoami. En macOS: uname -m y sw_vers. No son comandos intercambiables.','Consult About/System Information and compare with the appropriate terminal. Linux: uname -m and id. PowerShell: $PSVersionTable and whoami. macOS: uname -m and sw_vers. These commands are not interchangeable.')),
 P(B('Equipo propio asignado; sin cambios administrativos.','Assigned own device; no administrative changes.'),[
 S(B('Completa la ficha y separa host e invitado si hay VM.','Complete the record and separate host and guest if using a VM.'),B('No atribuyes la arquitectura del host a otro invitado sin comprobarla.','Do not assume the guest architecture from the host.')),
 S(B('Selecciona tu equipo en la guía de entorno del aula.','Select your device in the classroom environment guide.'),B('Ruta compatible o limitación explícita.','A compatible path or an explicit limitation.')),
 S(B('Describe recuperación y datos fuera del alcance.','Describe recovery and out-of-scope data.'),B('Plan previo a la primera modificación.','A plan before the first modification.'))],B('Ficha minimizada, alcance y recuperación.','Minimized record, scope and recovery.'),B('Distingues leer teoría de completar una práctica nativa.','Distinguish reading theory from completing a native lab.'),B('Cerrar solo las sesiones de prueba; ningún cambio de configuración.','Close only trial sessions; no configuration changes.'),B('Una imagen x86 no inicia en virtualización ARM.','An x86 image will not boot under ARM virtualization.'),B('Revisa arquitectura de host e invitado; no desactives seguridad ni uses imágenes desconocidas.','Check host and guest architecture; do not disable security or use unknown images.')),
 Q(B('¿PowerShell en macOS proporciona automáticamente AD DS local?','Does PowerShell on macOS automatically provide local AD DS?'),[B('Sí.','Yes.'),B('No; motor, módulos y servicios son distintos.','No; engine, modules and services differ.')],1,B('Utiliza un endpoint Windows autorizado para competencias que dependan de él.','Use an authorized Windows endpoint for skills depending on it.')),B('Ejecutar todo como administrador.','Running everything as administrator.'),B('El entorno forma parte de la solución.','The environment is part of the solution.'),['vbox','fusion','windows-arm'],['M01','M04']),
L('OS-C03',B('Diagnosticar sin probar a ciegas','Diagnose without guessing'),B('¿Qué prueba distingue tus dos explicaciones del fallo?','Which test distinguishes your two explanations of the failure?'),B('Convertir un síntoma en hipótesis, comprobación y conclusión.','Turn a symptom into hypotheses, a check and a conclusion.'),[
 C(B('Hecho frente a interpretación','Fact versus interpretation'),B('Anota el resultado esperado y observado, con el mensaje exacto y contexto mínimo. No traduzcas inmediatamente un timeout a servidor caído: también puede faltar ruta o existir filtrado. Una observación puede descartar una hipótesis sin demostrar otra. Trabaja con copias y conserva el estado inicial si investigas un incidente.','Record expected and observed results with the exact message and minimum context. Do not immediately translate a timeout into server down: routing or filtering may be involved. An observation can reject one hypothesis without proving another. Work on copies and preserve initial state when investigating an incident.'),B('El síntoma no es la causa.','The symptom is not the cause.')),
 C(B('Una variable por comprobación','One variable per check'),B('Elige la comprobación menos invasiva que cambie tu decisión. Consulta ayuda local, versión, identidad, ruta y permisos antes de reinstalar. Si cambias cinco configuraciones y el fallo desaparece, no sabes cuál importó ni qué rompiste. Define resultado positivo y negativo; registra salida y limitaciones.','Choose the least intrusive check that changes your decision. Consult local help, version, identity, path and permissions before reinstalling. If you change five settings and the failure disappears, you do not know which mattered or what else broke. Define positive and negative outcomes; record output and limitations.'),B('Cambiar menos permite aprender más del resultado.','Changing less lets you learn more from the result.')),
 C(B('Gestionar el bloqueo','Manage being stuck'),B('Marca el problema en el asistente y evita repetir una orden que no comprendes. Tras varios intentos sin información nueva, vuelve al objetivo, formula dos hipótesis y busca en la documentación oficial. Si falta plataforma, licencia o autorización, clasifica el bloqueo de entorno: no es un defecto de comprensión. Pedir ayuda con evidencia es una competencia.','Mark the problem in the assistant and avoid repeating a command you do not understand. After attempts yielding no new information, return to the goal, form two hypotheses and consult official documentation. Missing platform, license or authorization is an environment blocker, not a comprehension failure. Asking for help with evidence is a skill.'),B('El tiempo sirve para revisar el método, no para castigarte.','Time helps review the method, not punish you.'))],
 [B('Esperado / observado','Expected / observed'),B('Hipótesis','Hypothesis'),B('Una prueba segura','One safe test'),B('Decisión y evidencia','Decision and evidence')],
 E(B('Una ruta incorrecta','An incorrect path'),'GUI / CLI','',B('Se distingue archivo ausente de ruta de trabajo equivocada.','Distinguish a missing file from an incorrect working path.'),B('Crea una carpeta y un archivo ficticio. Intenta localizarlo desde otra carpeta usando una ruta relativa equivocada. Comprueba el directorio actual, formula la ruta correcta y repite sin elevar permisos.','Create a folder and fictitious file. Try locating it from another directory with an incorrect relative path. Check the working directory, formulate the correct path and retry without elevation.')),
 P(B('Carpeta propia y datos ficticios.','Own folder and fictitious data.'),[
 S(B('Predice el error de una ruta relativa desde otro directorio.','Predict the error of a relative path from another directory.'),B('Predicción escrita antes de comprobar.','Prediction written before checking.')),
 S(B('Registra esperado, observado y dos hipótesis.','Record expected, observed and two hypotheses.'),B('Hipótesis comprobables, no marcas comerciales.','Testable hypotheses, not brand names.')),
 S(B('Comprueba una ruta absoluta y explica el resultado.','Check an absolute path and explain the result.'),B('Corrección sin cambiar permisos ni protecciones.','A fix without changing permissions or protection.'))],B('Nota de problema y comprobación independiente.','Problem note and independent check.'),B('Otra persona puede repetir tu razonamiento.','Another person can reproduce your reasoning.'),B('Conserva la nota y retira los datos ficticios.','Keep the note and remove fictitious data.'),B('La primera hipótesis no explica el resultado.','The first hypothesis fails to explain the result.'),B('No ocultes el fallo: conserva la prueba y revisa la alternativa.','Do not hide the failure: retain the test and revisit the alternative.')),
 Q(B('¿Una orden que termina sin error acredita toda la solución?','Does a command finishing without error prove the entire solution?'),[B('No, falta verificar el resultado previsto.','No, the intended result must still be checked.'),B('Sí, siempre.','Yes, always.')],0,B('Comprueba el objeto y la función que intentabas recuperar.','Check the object and function you intended to recover.')),B('Reinstalar antes de identificar el síntoma.','Reinstalling before identifying the symptom.'),B('Predecir, comprobar y explicar.','Predict, check and explain.'),['os-book','nist-ir'],['M04','M10']),
L('OS-C04',B('Entregar resultados que ayuden a decidir','Deliver results that support decisions'),B('¿Qué necesita saber quien recibe tu solución?','What must the recipient know about your solution?'),B('Presentar un resultado técnico con impacto, opciones y límites.','Present a technical result with impact, options and limits.'),[
 C(B('Empieza por el objetivo','Start with the objective'),B('Una tarea no es valiosa por el número de comandos. Define a quién afecta, qué función necesita y cómo sabrás que funciona. Para una carpeta de proyecto: lectores leen, editores modifican y nadie recibe administración accidental. Esta definición permite comprobar el servicio y la restricción, no solo una pantalla de configuración.','A task is not valuable because of its command count. Define who is affected, which function is needed and how success is checked. For a project folder: readers read, editors modify and nobody accidentally receives administration. This lets you check both service and restriction, not just a settings screen.'),B('Éxito funcional y restricción prevista.','Functional success and intended restriction.')),
 C(B('Opciones con consecuencias','Options with consequences'),B('Compara mantener, corregir y sustituir según esfuerzo, impacto, reversibilidad y dependencias. No inventes ahorros ni atribuyas un riesgo eliminado por una demo. Una tabla breve con supuestos puede ser más útil que un informe largo sin decisión. Escala excepciones a quien tiene autoridad; no aceptes riesgos de negocio en nombre de otro.','Compare keeping, fixing and replacing using effort, impact, reversibility and dependencies. Do not invent savings or claim a demo eliminates risk. A short table with assumptions can be more useful than a long report without a decision. Escalate exceptions to the authorized owner; do not accept business risks for someone else.'),B('Justifica la alternativa, no solo la herramienta.','Justify the option, not just the tool.')),
 C(B('Una entrega operable','An operable handover'),B('Entrega objetivo, entorno, cambio, prueba, resultado, límites y recuperación. Añade responsable y siguiente comprobación. Usa identificadores ficticios y evidencia minimizada. Si usaste IA, indica qué revisaste tú y qué rechazaste. La IA puede proponer hipótesis; no es evidencia de que una prueba se haya ejecutado.','Deliver objective, environment, change, test, outcome, limits and recovery. Add the owner and next check. Use fictitious identifiers and minimized evidence. If using AI, state what you independently checked and rejected. AI can propose hypotheses; it is not evidence that a test ran.'),B('La siguiente persona debe poder continuar sin adivinar.','The next person must be able to continue without guessing.'))],
 [B('Objetivo','Goal'),B('Opciones','Options'),B('Evidencia','Evidence'),B('Decisión y siguiente acción','Decision and next action')],
 E(B('Informe de una página','One-page handover'),'Documento / Document','',B('Otra persona comprende el estado y reproduce la verificación.','Another person understands the state and reproduces verification.'),B('Reutiliza el problema de la lección anterior. Redacta conclusión al principio, evidencia después y una limitación explícita. Separa solución temporal y corrección sostenible.','Reuse the previous lesson problem. Put the conclusion first, evidence next and one explicit limitation. Separate a temporary workaround from a sustainable correction.')),
 P(B('Caso previo sin datos personales.','Previous case without personal data.'),[
 S(B('Resume objetivo y resultado en tres frases.','Summarize objective and result in three sentences.'),B('No confunde hipótesis con hechos.','Does not confuse hypotheses with facts.')),
 S(B('Compara dos opciones y justifica una.','Compare two options and justify one.'),B('Incluye esfuerzo, impacto y reversión.','Includes effort, impact and rollback.')),
 S(B('Pide a un compañero que reproduzca la comprobación.','Ask a peer to reproduce the check.'),B('Registra la desviación y mejora instrucciones.','Record deviations and improve instructions.'))],B('Resumen, tabla de opciones y revisión.','Summary, options table and review.'),B('Conclusión trazable y comunicación comprensible.','A traceable conclusion and understandable communication.'),B('No requiere cambios nuevos en sistemas.','Requires no new system changes.'),B('El compañero necesita una explicación oral no escrita.','The peer needs an unwritten explanation.'),B('Añade el contexto faltante y repite la entrega.','Add missing context and repeat the handover.')),
 Q(B('¿Una captura de configuración acredita acceso efectivo?','Does a settings screenshot prove effective access?'),[B('Sí.','Yes.'),B('No; se necesita la prueba correspondiente.','No; the relevant test is needed.')],1,B('La configuración declarada y su efecto se comprueban por separado.','Declared configuration and its effect are checked separately.')),B('Mucho detalle sin conclusión ni responsable.','Too much detail without a conclusion or owner.'),B('Explica resultado, evidencia, límite y siguiente acción.','Explain result, evidence, limit and next action.'),['nist-ir'],['M04','M32'])]
