"""Primary reference destinations. Versions must be checked for the actual lab."""
REFERENCES = {
'os-book': ('Operating Systems: Three Easy Pieces','https://pages.cs.wisc.edu/~remzi/OSTEP/'),
'bash':('GNU Bash manual','https://www.gnu.org/software/bash/manual/bash.html'),
'coreutils':('GNU Coreutils manual','https://www.gnu.org/software/coreutils/manual/coreutils.html'),
'systemd':('systemd documentation','https://systemd.io/'),
'openssh':('OpenSSH ssh(1)','https://man.openbsd.org/ssh'),
'ubuntu-network':('Ubuntu Server networking','https://documentation.ubuntu.com/server/how-to/networking/'),
'ubuntu-security':('Ubuntu security','https://ubuntu.com/security'),
'ubuntu-sssd':('Ubuntu SSSD integration','https://documentation.ubuntu.com/server/how-to/sssd/'),
'nist-ir':('NIST SP 800-61 Rev. 3','https://csrc.nist.gov/pubs/sp/800/61/r3/final'),
'nist-media':('NIST SP 800-88 Rev. 2','https://csrc.nist.gov/pubs/sp/800/88/r2/final'),
'powershell':('PowerShell pipelines','https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_pipelines'),
'ps-errors':('PowerShell error handling','https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_try_catch_finally'),
'windows-commands':('Windows commands','https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands'),
'ms-process':('Windows processes and threads','https://learn.microsoft.com/en-us/windows/win32/procthread/processes-and-threads'),
'ms-acl':('Windows access control','https://learn.microsoft.com/en-us/windows/win32/secauthz/access-control'),
'ms-profiles':('Windows user profiles','https://learn.microsoft.com/en-us/windows/win32/shell/user-profiles'),
'ms-tasks':('Windows Task Scheduler','https://learn.microsoft.com/en-us/windows/win32/taskschd/task-scheduler-start-page'),
'ms-events':('Get-WinEvent','https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.diagnostics/get-winevent'),
'ms-ad':('Active Directory Domain Services','https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/get-started/virtual-dc/active-directory-domain-services-overview'),
'ms-ldap':('LDAP signing','https://learn.microsoft.com/en-us/windows-server/identity/ad-ds/ldap-signing'),
'ms-smb':('SMB security','https://learn.microsoft.com/en-us/windows-server/storage/file-server/smb-security'),
'ms-network':('NetTCPIP PowerShell module','https://learn.microsoft.com/en-us/powershell/module/nettcpip/'),
'ms-tenant':('Tenant restrictions','https://learn.microsoft.com/en-us/entra/external-id/tenant-restrictions-v2'),
'ms-defender':('Microsoft Defender for Endpoint','https://learn.microsoft.com/en-us/defender-endpoint/'),
'ms-bitlocker':('BitLocker','https://learn.microsoft.com/en-us/windows/security/operating-system-security/data-protection/bitlocker/'),
'apple-security':('Apple Platform Security','https://support.apple.com/guide/security/welcome/web'),
'apple-apfs':('APFS','https://developer.apple.com/documentation/foundation/file_system/about_apple_file_system'),
'apple-terminal':('Terminal User Guide','https://support.apple.com/guide/terminal/welcome/mac'),
'apple-tcc':('Apple privacy controls','https://support.apple.com/guide/security/controlling-app-access-to-files-secddd1d86a6/web'),
'apple-launchd':('Apple launchd reference','https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPSystemStartup/Chapters/CreatingLaunchdJobs.html'),
'apple-network':('macOS network settings','https://support.apple.com/guide/mac-help/change-network-settings-mh11938/mac'),
'apple-filevault':('FileVault','https://support.apple.com/guide/security/volume-encryption-with-filevault-sec4c6dc1b6e/web'),
'apple-log':('Apple Console User Guide','https://support.apple.com/guide/console/welcome/mac'),
'apple-backup':('Back up with Time Machine','https://support.apple.com/en-us/104984'),
'zsh':('zsh manual','https://zsh.sourceforge.io/Doc/Release/'),
'vbox':('VirtualBox host/guest compatibility','https://docs.oracle.com/en/virtualization/virtualbox/7.2/user/Introduction.html'),
'fusion':('VMware Fusion on Apple Silicon','https://knowledge.broadcom.com/external/article/315602'),
'windows-arm':('Windows 11 Arm ISO','https://www.microsoft.com/en-us/software-download/windows11arm64'),
}
