/** View-model contract tests with a minimal in-memory DOM adapter.
 * They exercise application functions, not browser layout, CSS or native events.
 */
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
import * as stateApi from '../assets/state.js';import {text} from '../assets/i18n.js';import * as portable from '../assets/portable.js';
const data={es:JSON.parse(fs.readFileSync(new URL('../dist/course.json',import.meta.url))),en:JSON.parse(fs.readFileSync(new URL('../dist/course.en.json',import.meta.url)))};
let source=fs.readFileSync(new URL('../assets/app.js',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');source=source.slice(0,source.indexOf('const requested='));
source+='\nglobalThis.app={setLanguage,render,home,start,outline,moduleView,wizard,library,resource,search,showProgress,sharing,remember,persist,receive,present,drawSlide,state:()=>state,language:()=>language,course:()=>course,pending:()=>pendingTransfer};';
function environment(){
 const elements=new Map(),events=new Map();
 class Element{constructor(id){this.id=id;this.innerHTML='';this.textContent='';this.hidden=false;this.open=false;this.value='all';this.dataset={};this.handlers=new Map();this.tagName='DIV';}addEventListener(n,fn){this.handlers.set(n,fn);}setAttribute(){}focus(){}scrollIntoView(){}querySelectorAll(){return [];}querySelector(selector){return el(selector);}showModal(){this.open=true;}close(){this.open=false;}before(){}}
 function el(id){if(!elements.has(id))elements.set(id,new Element(id));return elements.get(id);}
 const storage=()=>({map:new Map(),writes:0,getItem(k){return this.map.get(k)||null;},setItem(k,v){this.map.set(k,v);this.writes++;}});
 const localStorage=storage(),sessionStorage=storage();let address=new URL('https://campus.example.test/');
 const location={get href(){return address.href;},get hash(){return address.hash;},set hash(h){address.hash=h;},get search(){return address.search;},get pathname(){return address.pathname;}};
 const document={querySelector:el,querySelectorAll:()=>[],documentElement:{lang:'es'},title:'',activeElement:new Element('none'),body:{classList:{toggle:()=>false,remove(){}}},addEventListener(n,f){events.set('doc:'+n,f);},createElement:()=>new Element('created'),getElementById:el};
 const globals={...stateApi,...portable,e:stateApi.escapeHTML,text,document,location,history:{replaceState(_,__,url){address=new URL(url,address);}},localStorage,sessionStorage,window:{addEventListener(n,f){events.set(n,f);},scrollTo(){}},navigator:{},URL,URLSearchParams,TextEncoder,TextDecoder,Blob,crypto:globalThis.crypto,console,setTimeout:()=>1,clearTimeout(){},confirm:()=>true,fetch:async path=>({ok:true,json:async()=>data[path.includes('.en.')?'en':'es']}),FormData};
 const context=vm.createContext(globals);vm.runInContext(source,context);return {app:context.app,el,location,document,localStorage,sessionStorage,events};
}
test('all ES/EN module tabs and 192 lab briefs generate nonempty safe markup',async()=>{const env=environment();for(const locale of ['es','en']){await env.app.setLanguage(locale);for(const m of env.app.course().modules){for(const tab of ['teoria','practicas','revision']){const html=env.app.moduleView(m,tab);assert.ok(html.includes(m.title));assert.ok(!html.includes('undefined'),m.id+tab);}for(const lab of m.labs){const html=env.app.wizard(m,lab);assert.ok(html.includes(lab.id));assert.ok(!html.includes('undefined'),lab.id);}}}});
test('language switch preserves progress and notes while changing document language',async()=>{const env=environment();await env.app.setLanguage('es');env.app.state().modules.M05.read=true;env.app.state().modules.M05.notes='User note';await env.app.setLanguage('en');assert.equal(env.app.state().modules.M05.read,true);assert.equal(env.app.state().modules.M05.notes,'User note');assert.equal(env.document.documentElement.lang,'en');assert.match(env.app.home(),/Learn\. Practise\. Verify\./);});
test('all library resources render in both editions',async()=>{const env=environment();for(const l of ['es','en']){await env.app.setLanguage(l);for(const r of env.app.course().resources)assert.ok(env.app.resource(r).includes(r.title));}});
test('notes are HTML escaped in the module view',async()=>{const env=environment();await env.app.setLanguage('es');env.app.state().modules.M01.notes='<script>window.unwanted=1</script>';const view=env.app.moduleView(data.es.modules[0]);assert.ok(view.includes('&lt;script&gt;'));assert.ok(!view.includes('<script>'));});
test('search supports multiple terms and handles markup as text',async()=>{const env=environment();await env.app.setLanguage('en');assert.match(env.app.search('bash files'),/search-result/);assert.ok(!env.app.search('<img src=x>').includes('<img src=x>'));});
test('received storage event does not write back or replace tab-local route',async()=>{const env=environment();await env.app.setLanguage('es');env.location.hash='#/modulo/M05/revision';env.app.render();const count=env.localStorage.writes;const other=stateApi.emptyState(data.es);other.lastRoute='#/modulo/M06';other.modules.M06.read=true;env.events.get('storage')({key:stateApi.KEY,newValue:JSON.stringify(other)});assert.equal(env.localStorage.writes,count);assert.equal(env.app.state().lastRoute,'#/modulo/M05/revision');assert.equal(env.app.state().modules.M06.read,true);});
test('tab-local continuation survives return to dashboard and language reload',async()=>{const env=environment();await env.app.setLanguage('es');env.location.hash='#/modulo/M05/practicas';env.app.render();env.location.hash='#/curso';env.app.render();await env.app.setLanguage('en');assert.match(env.app.home(),/id="resume" href="#\/modulo\/M05\/practicas"/);});
test('receiving a snapshot previews but does not import before confirmation',async()=>{const env=environment();await env.app.setLanguage('es');const other=stateApi.emptyState(data.es);other.modules.M05.read=true;const token=await portable.seal(data.es,other,'en');await env.app.receive(token);assert.ok(env.app.pending());assert.equal(env.app.state().modules.M05.read,false);assert.match(env.el('#main').innerHTML,/accept-transfer/);});
test('invalid snapshot never becomes pending',async()=>{const env=environment();await env.app.setLanguage('en');await env.app.receive('invalid');assert.equal(env.app.pending(),null);assert.match(env.el('#main').innerHTML,/expired or incompatible/);});
test('copy creation is explicit and no identity credential fields are rendered',async()=>{const env=environment();await env.app.setLanguage('en');assert.match(env.app.sharing(),/Create progress link/);assert.ok(!/type="(?:password|email)"/.test(env.app.sharing()));});
test('changing preview language keeps received progress pending, not imported',async()=>{const env=environment();await env.app.setLanguage('es');const other=stateApi.emptyState(data.es);other.modules.M05.read=true;await env.app.receive(await portable.seal(data.es,other,'en'));env.location.hash='#/recibir';await env.app.setLanguage('en');assert.match(env.el('#main').innerHTML,/Merge and continue/);assert.ok(env.app.pending());assert.equal(env.app.state().modules.M05.read,false);});
