import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {emptyState,progress} from '../assets/state.js';
import {compact,unpack,seal,unseal,mergeProgress,shareURL,MAX_TOKEN} from '../assets/portable.js';
const course=JSON.parse(fs.readFileSync(new URL('../dist/course.json',import.meta.url)));
const NOW=1789704000000;
const fixture=()=>{const s=emptyState(course);s.modules.M05={read:true,quiz:true,bookmarked:true,notes:'PRIVATE NOTE - NEVER SHARE'};s.labs.L05A={steps:[true,true,true,true,true],done:true};s.labs.L05B.steps=[true,false,true,false,false];s.lastRoute='#/modulo/M05/practica/L05B';return s;};
const data=()=>compact(course,fixture(),'en',NOW);
const reject=edit=>{const v=data();edit(v);assert.throws(()=>unpack(v,course,NOW));};
test('snapshot excludes notes, identities and credentials',()=>{const v=data();assert.deepEqual(Object.keys(v).sort(),['v','id','layout','issued','expires','route','language','modules','labs'].sort());assert.ok(!JSON.stringify(v).includes('PRIVATE'));assert.equal(v.modules.length,32);assert.equal(v.labs.length,96);});
test('every milestone and partial lab survives snapshot round trip',()=>{const result=unpack(data(),course,NOW);assert.equal(result.language,'en');assert.deepEqual(result.state.modules.M05,{read:true,quiz:true,bookmarked:true,notes:''});assert.deepEqual(result.state.labs.L05B.steps,fixture().labs.L05B.steps);assert.equal(result.state.lastRoute,fixture().lastRoute);assert.equal(progress(course,result.state).checked,3);});
test('empty progress round trip does not invent completion',()=>{const r=unpack(compact(course,emptyState(course),'es',NOW),course,NOW);assert.equal(progress(course,r.state).checked,0);});
test('all milestones are retained',()=>{const s=emptyState(course);Object.values(s.modules).forEach(m=>{m.read=m.quiz=m.bookmarked=true;});Object.values(s.labs).forEach(l=>{l.steps.fill(true);l.done=true;});assert.equal(progress(course,unpack(compact(course,s,'es',NOW),course,NOW).state).percent,100);});
test('expiry is enforced at the exact boundary',()=>{assert.throws(()=>unpack(data(),course,NOW+86400000));assert.doesNotThrow(()=>unpack(data(),course,NOW+86399999));});
test('future issue times are rejected',()=>reject(v=>{v.issued=NOW+120000;}));
test('maximum validity is bounded',()=>reject(v=>{v.expires=NOW+8*86400000;}));
test('negative validity rejected',()=>assert.throws(()=>compact(course,fixture(),'es',NOW,-1)));
test('unknown payload fields rejected',()=>reject(v=>{v.notes='not permitted';}));
test('wrong course rejected',()=>reject(v=>{v.id='another';}));
test('wrong version rejected',()=>reject(v=>{v.v=2;}));
test('unknown language rejected',()=>reject(v=>{v.language='xx';}));
test('mismatched module length rejected',()=>reject(v=>v.modules.pop()));
test('mismatched lab length rejected',()=>reject(v=>v.labs.push(0)));
test('out-of-range module flag rejected',()=>reject(v=>{v.modules[0]=8;}));
test('fractional lab flag rejected',()=>reject(v=>{v.labs[0]=1.1;}));
test('completed lab with missing phases rejected',()=>reject(v=>{v.labs[0]=32;}));
test('cross-module lab route rejected',()=>reject(v=>{v.route='#/modulo/M01/practica/L05A';}));
test('external route rejected',()=>reject(v=>{v.route='https://example.test';}));
test('AES-GCM encryption and decryption preserve milestones',async()=>{const token=await seal(course,fixture(),'en',NOW);assert.ok(token.length<MAX_TOKEN);const result=await unseal(token,course,NOW);assert.equal(result.state.modules.M05.read,true);assert.equal(result.state.modules.M05.notes,'');});
test('fresh random key and IV are generated per link',async()=>{const a=await seal(course,fixture(),'en',NOW),b=await seal(course,fixture(),'en',NOW);assert.notEqual(a,b);assert.notEqual(a.split('.')[1],b.split('.')[1]);assert.notEqual(a.split('.')[2],b.split('.')[2]);});
test('modified ciphertext is rejected',async()=>{const t=(await seal(course,fixture(),'es',NOW)).split('.');t[3]=(t[3][0]==='A'?'B':'A')+t[3].slice(1);await assert.rejects(unseal(t.join('.'),course,NOW));});
test('expired encrypted link is rejected',async()=>await assert.rejects(unseal(await seal(course,fixture(),'es',NOW),course,NOW+86400000)));
test('oversized token rejected before decryption',async()=>await assert.rejects(unseal('A'.repeat(MAX_TOKEN+1),course,NOW)));
test('malformed key or IV rejected',async()=>{const p=(await seal(course,fixture(),'es',NOW)).split('.');p[1]='AAAA';await assert.rejects(unseal(p.join('.'),course,NOW));});
test('merging preserves local notes and combines marks',()=>{const local=emptyState(course);local.modules.M05.notes='Local private note';local.modules.M01.read=true;local.labs.L05B.steps[1]=true;const result=mergeProgress(local,unpack(data(),course,NOW).state,course);assert.equal(result.modules.M05.notes,'Local private note');assert.equal(result.modules.M01.read,true);assert.equal(result.modules.M05.quiz,true);assert.deepEqual(result.labs.L05B.steps,[true,true,true,false,false]);assert.equal(result.labs.L05B.done,false);assert.equal(local.modules.M05.quiz,false,'inputs must not mutate');});
test('merging is idempotent for learning milestones',()=>{const a=unpack(data(),course,NOW).state,b=mergeProgress(emptyState(course),a,course),c=mergeProgress(b,a,course);assert.deepEqual(b.modules,c.modules);assert.deepEqual(b.labs,c.labs);});
test('share URL drops credentials and previous query',()=>{const url=new URL(shareURL('https://user:pass@campus.example.test/course/?secret=bad#/progreso','#/modulo/M05','en'));assert.equal(url.username,'');assert.equal(url.password,'');assert.equal(url.search,'?lang=en');assert.equal(url.hash,'#/modulo/M05');});
test('transfer payload is in fragment, not server path or query',async()=>{const token=await seal(course,fixture(),'es',NOW);const url=new URL(shareURL('https://campus.example.test/','#/transfer/'+token,'es'));assert.ok(!url.search.includes(token));assert.ok(!url.pathname.includes(token));assert.ok(url.hash.includes(token));});
test('non-secure public origins and executable schemes rejected',()=>{for(const u of ['http://campus.example.test/','javascript:alert(1)','file:///tmp/a'])assert.throws(()=>shareURL(u,'#/curso','en'));});
test('localhost development URL supported',()=>assert.match(shareURL('http://127.0.0.1:8788/','#/modulo/M01','es'),/^http:\/\/127\.0\.0\.1:8788/));
test('reordered catalogue is rejected rather than mapping marks to another module',()=>{const changed={...course,modules:[...course.modules].reverse()};assert.throws(()=>unpack(data(),changed,NOW));});
test('unsafe timestamp addition rejected',()=>assert.throws(()=>compact(course,fixture(),'es',Number.MAX_SAFE_INTEGER,2)));
test('invalid verification clock rejected',()=>assert.throws(()=>unpack(data(),course,NaN)));
