import test from 'node:test';
import assert from 'node:assert/strict';
import {EMPTY,validateProgress,parseImport,loadProgress,metrics,validLabUrl,searchLessons,STORAGE_KEY} from '../assets/state.js';
const lessons=[{id:'m01-l01',title:'Identidad y permisos',summary:'Linux',objectives:['Comprender sudo'],steps:[{command:'id'},{command:'pwd'}],quiz:[{options:['A','B','C','D'],answer:2}]}];
test('progress roundtrip preserves plain text and independent evidence',()=>{const a=EMPTY();a.completed=['m01-l01'];a.notes['m01-l01']='<img src=x onerror=alert(1)>';a.quiz['m01-l01']={0:2};a.steps['m01-l01']=[1];a.evidence['m01-l01']='explained';const b=parseImport(JSON.stringify(a),lessons);assert.equal(b.notes['m01-l01'],a.notes['m01-l01']);assert.deepEqual(metrics(b,lessons),{completed:1,total:1,percent:100,answered:1,correct:1,accuracy:100,practiced:1,steps:1});});
test('foreign courses and oversized imports cannot replace progress',()=>{assert.throws(()=>parseImport(JSON.stringify({...EMPTY(),course:'other'}),lessons));assert.throws(()=>parseImport(' '.repeat(2000001),lessons));});
test('invalid indices, notes, and prototype payload are rejected or stripped',()=>{const a=EMPTY();a.quiz['m01-l01']={0:9};assert.throws(()=>validateProgress(a,lessons));a.quiz={};a.steps['m01-l01']=[4];assert.throws(()=>validateProgress(a,lessons));a.steps={};a.notes['m01-l01']='x'.repeat(6001);assert.throws(()=>validateProgress(a,lessons));const raw=JSON.parse('{"schema":1,"course":"smartkea-term-linux","completed":[],"notes":{"__proto__":{"polluted":true}}}');const b=validateProgress(raw,lessons);assert.equal({}.polluted,undefined);assert.deepEqual(b.notes,{});});
test('corrupt stored progress leaves storage untouched and reports recovery',()=>{const storage={getItem:k=>k===STORAGE_KEY?'broken':null,setItem:()=>{throw new Error('must not overwrite')}};const result=loadProgress(storage,lessons);assert.ok(result.error);assert.equal(result.state.completed.length,0);});
test('lab URL enforces scheme, exact origin, separate origin and no credentials',()=>{const good={url:'https://lab.example.org/',allowedOrigins:['https://lab.example.org']};assert.equal(validLabUrl(good,'https://smartkea.com'),good.url);for(const url of ['http://lab.example.org/','https://lab.example.org.evil.test/','https://user:secret@lab.example.org/','https://lab.example.org/?arg=sh','https://lab.example.org/#cmd'])assert.equal(validLabUrl({...good,url},'https://smartkea.com'),null);assert.equal(validLabUrl(good,'https://lab.example.org'),null);});
test('search matches accented titles and actual commands',()=>{assert.equal(searchLessons(lessons,'permisos').length,1);assert.equal(searchLessons(lessons,'ID').length,1);assert.equal(searchLessons(lessons,'nmap').length,0);});

test('search finds commands beyond a long explanation',()=>{const l={...lessons[0],summary:'a'.repeat(1000),steps:[{command:'docker compose'}]};assert.equal(searchLessons([l],'docker').length,1);});
test('maximum text notes across all lessons survive export/import',()=>{const all=Array.from({length:48},(_,i)=>({...lessons[0],id:'lesson-'+i}));const data=EMPTY();for(const l of all)data.notes[l.id]='😀'.repeat(3000);assert.equal(Object.keys(parseImport(JSON.stringify(data),all).notes).length,48);});
